### PR TITLE
Switch to cimg namespaced circleci images

### LINKED ISSUE #43: Investigate using Circle's `cimg` docker images
Circle is replacing their current docker images with [these new ones](https://github.com/CircleCI-Public/cimg-overview), which are in various states of stability.

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes #43

### CODE REVIEW

**Comment by cjcolvar** [comment]
I reran the build after pushing a dev:alpha and everything passed but github isn't removing the failed check above.

**Comment by cjcolvar** [comment]
This should probably be tested on a few repos before being merged/released.

**Comment by mark-dce** [comment]
@cjcolvar I'm getting an error for the redis container when trying to build with the new orb.
```
version: 2.1
orbs:
    samvera: samvera/circleci-orb@dev:alpha
. . . 
        executor:
            name: samvera/ruby_fcrepo_solr_redis_postgres
```

gives me the following error on my CircleCI builds
```
Starting container cimg/redis:4
Digest: sha256:568c85fa34a46bbd4cac39967908d57cdfb37668e0b59abe9ca7eebdd7f58e43
Warning: No authentication provided, using CircleCI credentials for pulls from Docker Hub.
  image cache not found on this host, downloading cimg/redis:4

Error response from daemon: manifest for cimg/redis:4 not found: manifest unknown: manifest unknown
```

From what I can see scanning the documentation at the link below, it looks like CircleCI is not providing newer images for Service Images (like Redis) so we would need to continue using the legacy namespace for `redis` and `postgres`.

> **Service images**
>Service images are convenience images for services like databases. These images should be listed after language images so they become secondary service containers.
>
>CircleCI maintains *legacy images* for the services below.
> . . .
> * PostgreSQL
> * Redis
> . . .
>For example, if you want the `circleci/postgres:9.5-postgis` image to use RAM volume, use the `circleci/postgres:9.5-postgis-ram` image.
>
> **Next-gen service images**
>CircleCI is working on adding next-gen service convenience images. Checkout CircleCI’s Developer Hub for the latest available service images.

from https://circleci.com/docs/2.0/circleci-images/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-maxConv-auth-nb&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQiAqvaNBhDLARIsAH1Pq53fYuCFlrh2J2oI7OznAA3qUJ9A8yQRjeLoDU0Ti0i3GAxCpiHCZRcaArU_EALw_wcB#service-images

**Comment by cjcolvar** [comment]
It looks like there is a `cimg/redis` image in dockerhub but only for versions 5.0, 6.0, and 6.2.  CircleCI hasn't included it in their list of convenience images though (see https://circleci.com/developer/images).  I've updated this PR to default to version 6.2 which should have pushed a new dev:alpha version of the orb.  @mark-dce could you test again?

Since CircleCI doesn't have it in their list should we switch over to the official redis image?

**Comment by rotated8** [comment]
@cjcolvar I'm in favor of switching over to the official redis images. They're smaller (6.2.6 is~400 MB vs ~40 MB or ~10 MB for the alpine variants) and support more versions.

**Review by mlooney — APPROVED** [review]
Looks good to me, we got past our image naming issues, though we did then immediately run into the solr 8 security.json issue

**Pull request merged**
